# Generated by Django 5.2.7 on 2025-11-17 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0002_documentacion_id_cliente_domicilio_id_cliente_and_more'),
        ('app_Empresa', '0002_alter_on_premise_fecha_de_compra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AlterModelOptions(
            name='documentacion',
            options={'ordering': ['-fecha_registro']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='app_Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentaciones', to='app_Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='garante',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garantess', to='app_Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='empresa_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='ci',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='documentacion',
            name='id_cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentacion', to='app_Cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='garante',
            name='id_domicilio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garante', to='app_Cliente.domicilio'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
