# Generated by Django 5.2.7 on 2025-11-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cliente', '0003_alter_cliente_options_alter_documentacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='documento_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='croquis_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='extracto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
