# Generated by Django 5.2.7 on 2025-11-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_User', '0002_alter_perfiluser_imagen_url'),
    ]

    operations = [
    ]
