# Generated by Django 5.2.7 on 2025-11-17 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Empresa', '0002_alter_on_premise_fecha_de_compra'),
        ('app_User', '0004_groupdescripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdescripcion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='app_Empresa.empresa'),
        ),
    ]
