# Generated by Django 5.2.7 on 2025-11-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='Moneda',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='credito',
            name='enum_estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('SOLICITADO', 'SOLICITADO'), ('DESENBOLSADO', 'DESENBOLSADO'), ('FINALIZADO', 'FINALIZADO')], default='SOLICITADO', max_length=20),
        ),
    ]
