# Generated by Django 5.2.7 on 2025-11-17 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Credito', '0002_alter_credito_moneda_alter_credito_enum_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='fase_actual',
            field=models.CharField(choices=[('FASE_1_SOLICITUD', 'Datos de la solicitud'), ('FASE_2_DOCUMENTACION', 'Documentación personal'), ('FASE_3_LABORAL', 'Información laboral'), ('FASE_4_DOMICILIO', 'Domicilio'), ('FASE_5_GARANTE', 'Datos del garante'), ('FASE_6_REVISION', 'Revisión y aprobación'), ('FASE_7_DESEMBOLSO', 'Desembolso del crédito'), ('FASE_8_FINALIZADO', 'Crédito finalizado')], default='FASE_1_SOLICITUD', max_length=30),
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='credito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credito',
            name='razon_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_anterior', models.CharField(blank=True, choices=[('FASE_1_SOLICITUD', 'Datos de la solicitud'), ('FASE_2_DOCUMENTACION', 'Documentación personal'), ('FASE_3_LABORAL', 'Información laboral'), ('FASE_4_DOMICILIO', 'Domicilio'), ('FASE_5_GARANTE', 'Datos del garante'), ('FASE_6_REVISION', 'Revisión y aprobación'), ('FASE_7_DESEMBOLSO', 'Desembolso del crédito'), ('FASE_8_FINALIZADO', 'Crédito finalizado')], max_length=30, null=True)),
                ('fase_nueva', models.CharField(choices=[('FASE_1_SOLICITUD', 'Datos de la solicitud'), ('FASE_2_DOCUMENTACION', 'Documentación personal'), ('FASE_3_LABORAL', 'Información laboral'), ('FASE_4_DOMICILIO', 'Domicilio'), ('FASE_5_GARANTE', 'Datos del garante'), ('FASE_6_REVISION', 'Revisión y aprobación'), ('FASE_7_DESEMBOLSO', 'Desembolso del crédito'), ('FASE_8_FINALIZADO', 'Crédito finalizado')], max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_agregados', models.JSONField(blank=True, default=dict)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='app_Credito.credito')),
                ('usuario_cambio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
