# Generated by Django 5.2.7 on 2025-11-17 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Credito', '0003_credito_fase_actual_credito_fecha_actualizacion_and_more'),
        ('app_Empresa', '0002_alter_on_premise_fecha_de_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_credito',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Empresa.empresa'),
        ),
    ]
